version: '3.8'

services:
  todo-app:
    build: .
    container_name: todo-app-container
    ports:
      - "3000:8080"
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge